pipeline {
    agent any
    
    stages {
        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy Frontend') {
            steps {
                script {
                    sh 'kill $(lsof -t -i:3000) || true'
                    
                    dir('frontend') {
                        sh 'nohup npm run preview -- --port 3000 > frontend.log 2>&1 &'
                    }
                    
                    sleep 5
                }
            }
        }
        
        stage('Health Check') {
            steps {
                sh 'curl -f http://localhost:3000 || echo Frontend check failed'
            }
        }
    }
}
