plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.dependency.management)
}

group = 'com.hospitalmgmt.rsmlh'
version = '1.0.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.spring.web
    implementation libs.spring.data.jpa
    implementation libs.spring.actuator
    implementation libs.jackson.databind
    implementation libs.jackson.jsr310
    implementation libs.springdoc.openapi
    implementation libs.hibernate.validator

    developmentOnly libs.spring.devtools

    runtimeOnly libs.postgresql
    runtimeOnly libs.h2
    runtimeOnly libs.spring.docker.compose

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testImplementation libs.spring.test
    testRuntimeOnly libs.h2
}

test {
    useJUnitPlatform()
}
