pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build & Deploy Backend') {
            steps {
                dir('backend') {
                    sh 'docker build -t hospital-app .'
                    sh 'docker stop hospital-app-container 2>/dev/null || true'
                    sh 'docker rm hospital-app-container 2>/dev/null || true'
                    sh 'docker run -d --name hospital-app-container -p 8081:8080 hospital-app'
                    sh 'docker image prune -af --filter "until=24h"'
                    sh 'docker builder prune -af --filter "until=24h"'
                }
            }
        }
        stage('Build & Deploy Frontend') {
            steps {
                build job: 'frontend-deploy', wait: false
            }
        }
    }
    post {
        failure {
            echo 'Deployment failed!'
        }
        success {
            echo 'Deployment successful!'
        }
    }
}
