#db
spring.datasource.url=jdbc:h2:file:./data/hospitaldb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.enabled=false

server.port = 8080

logging.level.org.springframework.web=DEBUG
logging.level.com.hospitalmgmt.rsmlh.hospital_app=DEBUG
logging.file.name=logs/app-debug.log
logging.console.enabled=false

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.jpa.open-in-view=false
logging.level.org.springdoc=DEBUG