package com.hospitalmgmt.rsmlh.hospital_app.rsmlh_entity;

public enum Specialization {
    CARDIOLOGY,
    DERMATOLOGY,
    EMERGENCY_MEDICINE,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GENERAL_PRACTICE,
    GERIATRICS,
    HEMATOLOGY,
    INFECTIOUS_DISEASE,
    INTERNAL_MEDICINE,
    NEPHROLOGY,
    NEUROLOGY,
    OBSTETRICS_AND_GYNECOLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIOLOGY,
    RHEUMATOLOGY,
    SURGERY,
    UROLOGY
}
